<a href="https://colab.research.google.com/github/LemdjoM/Arduino/blob/master/labs/11%20-%20Classification%202/Exercises/classification_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align="center"> EXERCISES - CLASSIFICATION 2</h1>

<div>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Logo_Universit%C3%A9_de_Lausanne.svg/2000px-Logo_Universit%C3%A9_de_Lausanne.svg.png" style="padding-right:10px;width:240px;float:left"/></td>
<h2 style="white-space: nowrap">Business Intelligence and Analytics</h2></td>
<hr style="clear:both">
<p style="font-size:0.85em; margin:2px; text-align:justify">

</div>

## KNN and Decision Trees

In this lab we will work on K Nearest Neighbor and Decision Trees for classification.

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import collections  as mc
%load_ext autoreload
%autoreload 2
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
sns.set_style("white")

In [2]:
np.random.seed(72)

### Load data

We will start with the `heart disease` dataset from last week. Here's a description of the attributes in the data-set:

> 1. age
> 2. sex
> 3. chest pain type (4 values)
> 4. resting blood pressure
> 5. serum cholestoral in mg/dl
> 6. fasting blood sugar > 120 mg/dl
> 7. resting electrocardiographic results (values 0,1,2)
> 8. maximum heart rate achieved
> 9. exercise induced angina
> 10. target: 1: presence 0: absence of a heart disease

In [3]:
# data-set: heart.csv
df = pd.read_csv("https://media.githubusercontent.com/media/michalis0/Business-Intelligence-and-Analytics/master/data/heart_2025.csv", delimiter=';')
df.head()

age sex cp  trestbps  chol  fbs restecg  thalach exang  target
0   67   M  A       160   286   no       A      108   yes       0
1   67   M  A       120   229   no       A      129   yes       0
2   62   F  A       140   268   no       A      160    no       0
3   63   M  A       130   254   no       A      147    no       0
4   53   M  A       140   203  yes       A      155   yes       0

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import datasets

### K-neirest neighbor classification

Let's start with only 2 features: age and maximum heart rate achieved (thalach). Define your features and target variable.

In [8]:
X = df[['age','thalach']]
y = df['target']
X.shape

(286, 2)

\Split your data set into train and test subsets. Use the sklearn `train_test_split` with `test_size=0.2` and `random_state=72`.

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=72, test_size=0.2)
X_train.describe()

age     thalach
count  228.000000  228.000000
mean    54.114035  148.969298
std      9.087687   22.597102
min     34.000000   90.000000
25%     47.000000  132.000000
50%     55.000000  152.000000
75%     61.000000  165.000000
max     77.000000  192.000000

Define a KNN model with __3__ number of neighbors.


In [10]:
#Create model
model = KNeighborsClassifier(n_neighbors=3)

Fit your model now using the train set.

In [11]:
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Compare your train and test accuracy for the KNN model.

In [13]:
# train accuracy
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(model.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 0.80


In [14]:
# test accuracy
print('Accuracy of KNN classifier on test set: {:.2f}'
     .format(model.score(X_test, y_test)))

Accuracy of KNN classifier on test set: 0.59




```
# This is formatted as code
```

Calculate the base rate

In [17]:
#Compute the base rate
#Base rate = (most frequent class)/(total observations)
nbr_heart_disease = df.loc[df["target"] == 1].shape[0]
print("#Heart disease = ", nbr_heart_disease)

nbr_no_heart_disease = df.loc[df["target"] == 0].shape[0]
print("#No heart disease = ", nbr_no_heart_disease)

# Compute base rate
total_samples = df.shape[0]
base_rate = max(nbr_heart_disease, nbr_no_heart_disease) / total_samples

print("Baserate = ", base_rate)

#Heart disease =  148
#No heart disease =  138
Baserate =  0.5174825174825175


Show the confusion matrix for the KNN model.

In [18]:
#Confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)

# Get the confusion matrix
confusion_matrix(y_test, y_pred)
#confusion_matrix("YOUR CODE HERE")

array([[17,  9],
       [15, 17]])

For which combination of K (number of neighbors), the value `p` (distance metric), and weight do we obtain the best accurary? Use the values indicated in the following code cell.

<h2>Important: This question answers the Moodle quiz question 1. </h2>

In [19]:
n_neighbors = [3,5,6,7]
p_values = [1,2] #  1 is Manhattan distance, 2 is Euclidean distance
weight = 'distance'
for n in n_neighbors:
    for p in p_values:
        model = KNeighborsClassifier(n_neighbors=n, p=p, weights=weight)
        model.fit(X_train, y_train)
        print("accuracy for k = " + str(n) + ", p = " + str(p) + ", weight = " + weight + " : " + str(np.round(model.score(X_test, y_test), 3)))

accuracy for k = 3, p = 1, weight = distance : 0.569
accuracy for k = 3, p = 2, weight = distance : 0.552
accuracy for k = 5, p = 1, weight = distance : 0.638
accuracy for k = 5, p = 2, weight = distance : 0.603
accuracy for k = 6, p = 1, weight = distance : 0.569
accuracy for k = 6, p = 2, weight = distance : 0.603
accuracy for k = 7, p = 1, weight = distance : 0.638
accuracy for k = 7, p = 2, weight = distance : 0.638


Now, using the KNN model with the best parameters you achieved above, let's try to predict the class and probability of correct classification for Age = 50, Thalach = 130 and Age = 70, Thalach = 160

In [20]:
# define and train the model with the best parameters
model = KNeighborsClassifier(n_neighbors=5, p=1, weights='distance')
model.fit(X_train, y_train)

KNeighborsClassifier(p=1, weights='distance')

In [22]:
# Define the new samples (Age = 50, Thalach = 130) and (Age = 70, Thalach = 160)
new_samples = np.array([[50, 130], [70, 160]])
print("Predicted Classes:", model.predict(new_samples))
#print("Predicted Probabilities:", model.predict_proba(new_samples))

Predicted Classes: [0 1]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


Now let's try more numerical features and see if the accuracy improves.
We will use now "age", "thalach", "trestbps" and "chol".
Define your features and your target variable.

In [23]:
X = df[["age","thalach","trestbps","chol"]]
y = df["target"]
X.shape

(286, 4)

Split your data set into train and test subsets. Again use `test_size=0.2, random_state=72`.

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=72, test_size=0.2)
X_train.describe()

age     thalach    trestbps        chol
count  228.000000  228.000000  228.000000  228.000000
mean    54.114035  148.969298  132.026316  247.837719
std      9.087687   22.597102   16.920108   53.093343
min     34.000000   90.000000  100.000000  126.000000
25%     47.000000  132.000000  120.000000  212.000000
50%     55.000000  152.000000  130.000000  243.000000
75%     61.000000  165.000000  140.000000  277.250000
max     77.000000  192.000000  200.000000  564.000000

Standardize your data using the sklearn standard scaler.

In [25]:
standardize = StandardScaler()
standardize.fit(X_train)

StandardScaler()

In [27]:
X_train = standardize.transform(X_train)
X_test = standardize.transform(X_test)
pd.DataFrame(X_train, columns=['mass', 'width', 'height', 'color_score']).describe()

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


mass       width      height  color_score
count  228.000000  228.000000  228.000000   228.000000
mean    -5.967756   -6.606912   -7.820092    -4.678233
std      0.110524    0.044448    0.059362     0.018918
min     -6.212381   -6.722904   -7.932452    -4.721645
25%     -6.054276   -6.640291   -7.862285    -4.691002
50%     -5.956981   -6.600951   -7.827201    -4.679957
75%     -5.884009   -6.575380   -7.792118    -4.667753
max     -5.689418   -6.522271   -7.581617    -4.565581

Fit your model using the train data. Let's use the same KNN model that you defined above.



In [28]:
model.fit(X_train,y_train)

KNeighborsClassifier(p=1, weights='distance')

Compare your train and test accurary.

In [29]:
# train accuracy
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(model.score(X_train, y_train)))

Accuracy of KNN classifier on training set: 1.00


In [30]:
# test accuracy
print('Accuracy of KNN classifier on test set: {:.2f}'
     .format(model.score(X_test, y_test)))

Accuracy of KNN classifier on test set: 0.64


In [31]:
#Confusion matrix for the test predictions
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)

# Get the confusion matrix
confusion_matrix(y_test, y_pred)

array([[17,  9],
       [12, 20]])

**Question:** Compute the recall and precision of the model for the test set.

In [32]:
# Compute precision and recall
from sklearn.metrics import precision_score, recall_score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

# Display results
print(f"Precision: {precision:.3f}")
print(f"Recall: {recall:.3f}")

Precision: 0.690
Recall: 0.625


### Decision tree classification

We will now use the decision tree algorithm for classification. We will use the same dataset as the above exercise, i.e., we use the 4 features "age", "thalach", "trestbps", "chol".

Import the necessary libraries for decision tree classification, define the model and train your model. The test it. What is the accuracy of your model (using the test set)?

In [33]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth = 1)
model.fit(X_train, y_train)
print(model.score(X_test, y_test))

0.6896551724137931


How can you improve your model?

As you may know increasing the depth of the decision tree can improve its accuracy, but it can also lead to overfitting! Using the range of values for depth provided in the cell below, find the depth value that leads to the best test accuracy.

<h2>Important: This question answers the Moodle quiz question 2. </h2>

In [36]:
best_acc = 0
for depth in range(1, 8):
  model = DecisionTreeClassifier(max_depth = depth)
  model.fit(X_train,y_train)
  accuracy = model.score(X_test,y_test)
  if accuracy > best_acc:
    best_acc = accuracy
    best_depth = depth
print("best depth: ", best_depth)

best depth:  1
